### ISSUE TITLE
Update CLDR

### ISSUE THREAD

**Issue by charles-dexter-ward** [dojo/util#84]
The CLDR shipped with dojo 1.16.3 is the version 30, if I'm correct.
The last version should be shipped.
Tried to build from CLDR 38 (following https://dojotoolkit.org/reference-guide/1.10/dojo/cldr.html) but there are some errors during the build process.

Ie:

Syntax error in C:\Users\username\Downloads\dojo-release-1.16.3-src\dojo\cldr\nls\de\number.js// generated from ldml/main/*.xml, xpath: ldml/numbers

and, the number.js for de is malformed:
```
....
	'currencyFormat-short':"0 Mrd'.' ¤",
	'currencyFormat-short':"0 Mrd'.' ¤",
	'currencyFormat-short':"00 Mrd'.' ¤",
	'currencyFormat-short':"00 Mrd'.' ¤",
	'currencyFormat-short':"000 Mrd'.' ¤",
	'currencyFormat-short':"000 Mrd'.' ¤",
	'currencyFormat-short':"0 Bio'.' ¤",
	'currencyFormat-short':"0 Bio'.' ¤",
	'currencyFormat-short':"00 Bio'.' ¤",
	'currencyFormat-short':"00 Bio'.' ¤",
	'currencyFormat-short':"000 Bio'.' ¤",
	'currencyFormat-short':"000 Bio'.' ¤"{0} Tag{0} Tage{0}. Abzweigung nach rechts nehmen… für {0} …… mit {0} …Anstatt {0} …{0} kostet (kosten) € 3,50.Die {0} ist …Der {0} ist …Das {0} ist …
})
```

**Comment by charles-dexter-ward** [comment]
I was able to re-build the nls file using CLDR 38 modifing:

utils/buildscripts/cldr/number.xsl

and adding

"minimalPairs" to the ignore group.

`<xsl:template name="ignore" match="defaultNumberingSystem | otherNumberingSystems | currencies | miscPatterns | minimumGroupingDigits | minimalPairs"></xsl:template>`

but I don't now if the new generated nls is compatible with the i18n functions.

**Comment by dasa** [comment]
Would this also fix this? https://github.com/dojo/dojo/issues/388

**Comment by dylans** [comment]
> Would this also fix this? [dojo/dojo#388](https://github.com/dojo/dojo/issues/388)

Possibly, I had missed this issue. If anyone wants to put together a PR to fix all of this, I'm happy to review and land it and do an updated release.

**Comment by edhager** [comment]
@charles-dexter-ward The current version of Dojo down to version 1.13 has been updated with CLDR 38.1.  Can you verify the updates and close this ticket if everything is resolved?

**Comment by charles-dexter-ward** [comment]
@edhager I have verified the commit in https://github.com/dojo/util/pull/85

Thanks.
